#version: "3.9"
#services:
#  db:
#    image: ankane/pgvector:latest       # Postgres 16 + pgvector pre-built
#    container_name: mailmule_pg
#    environment:
#      POSTGRES_USER: mailmule
#      POSTGRES_PASSWORD: mailmule
#      POSTGRES_DB: mailmule
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data  # keeps data on disk
#    ports:
#      - "5432:5432"

version: '3.8'

services:
  app:
    build: .
    ports:
      - "5432:5432"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:159753@db:5432/postgres  # Example connection string

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
